// ============================================================
// AP3X — printReportUtils.js — Run 8
// ============================================================
import { EXPORT_SAFETY_NOTICE } from "../core/constants.js";

export function createPrintSafeStyles() {
  return `
    body { font-family: Georgia, serif; background: #fff; color: #111; margin: 0; padding: 0; }
    .print-doc { max-width: 820px; margin: 0 auto; padding: 40px; }
    h1 { font-size: 1.8rem; border-bottom: 2px solid #111; padding-bottom: 8px; margin-bottom: 24px; }
    h2 { font-size: 1.2rem; border-bottom: 1px solid #ccc; padding-bottom: 4px; margin-top: 32px; }
    h3 { font-size: 1rem; margin-top: 20px; }
    p, li { font-size: 0.9rem; line-height: 1.7; }
    .notice { border: 1px solid #111; padding: 12px 16px; background: #f9f9f9; font-size: 0.8rem; margin: 24px 0; }
    .score { font-weight: bold; font-size: 1.1rem; }
    table { border-collapse: collapse; width: 100%; margin: 16px 0; }
    th, td { border: 1px solid #ccc; padding: 6px 12px; font-size: 0.85rem; text-align: left; }
    th { background: #f0f0f0; }
    .footer { margin-top: 48px; font-size: 0.75rem; color: #666; border-top: 1px solid #ccc; padding-top: 12px; }
    @media print {
      .no-print { display: none !important; }
      body { -webkit-print-color-adjust: exact; }
    }
  `;
}

function safeArr(v) { return Array.isArray(v) && v.length > 0 ? v : []; }
function esc(s) { return String(s || "").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;"); }

export function createPrintHTML(exportPack) {
  if (!exportPack) return "<html><body><p>No export pack available.</p></body></html>";
  const cr   = exportPack.clientReport   || {};
  const risk = exportPack.riskScorecard  || {};
  const road = exportPack.implementationRoadmap || {};
  const osr  = exportPack.originalitySafetyReport || {};

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>${esc(exportPack.title)} — AP3X Export</title>
<style>${createPrintSafeStyles()}</style>
</head>
<body>
<div class="print-doc">
  <h1>${esc(exportPack.title)}</h1>
  <p><strong>Generated:</strong> ${new Date().toLocaleString()} &nbsp; <strong>Pack ID:</strong> ${esc(exportPack.id)}</p>
  <div class="notice"><strong>⚖ Originality &amp; Legal Safety Notice</strong><br/>${esc(EXPORT_SAFETY_NOTICE)}</div>

  <h2>Client-Ready Architecture Report</h2>
  <h3>Executive Summary</h3><p>${esc(cr.executiveSummary)}</p>
  <h3>Architecture Overview</h3><p>${esc(cr.architectureOverview)}</p>
  <h3>Risk Summary</h3><p>${esc(cr.riskSummary)}</p>
  <h3>Recommendations</h3>
  <ul>${safeArr(cr.recommendations).map((r) => `<li>${esc(r)}</li>`).join("")}</ul>
  <h3>Next Steps</h3>
  <ul>${safeArr(cr.nextSteps).map((s) => `<li>${esc(s)}</li>`).join("")}</ul>

  <h2>Risk Scorecard</h2>
  <p class="score">Overall Risk: ${esc(risk.overallRisk)}</p>
  <table>
    <tr><th>Area</th><th>Score</th><th>Label</th></tr>
    ${["architectureCompleteness","dataClarity","buildReadiness","originalitySafety"].map((a) =>
      risk[a] ? `<tr><td>${a.replace(/([A-Z])/g," $1").trim()}</td><td>${risk[a].score}%</td><td>${risk[a].label}</td></tr>` : ""
    ).join("")}
  </table>
  <p>${esc(risk.recommendation)}</p>

  <h2>Implementation Roadmap</h2>
  ${safeArr(road.phases).map((ph) => `<h3>Phase ${ph.phase} — ${esc(ph.title)}</h3><p>${esc(ph.mission)}</p>`).join("")}

  <div class="footer">
    Generated by AP3X BUILD CONTROL OS™ Export Centre — Run 8.
    Original implementation required. Architecture patterns only.
    ${esc(EXPORT_SAFETY_NOTICE)}
  </div>
</div>
</body>
</html>`;
}

export function openPrintWindow(exportPack) {
  try {
    const html = createPrintHTML(exportPack);
    const win  = window.open("", "_blank");
    if (!win) return { success: false, error: "Popup blocked. Allow popups and try again." };
    win.document.write(html);
    win.document.close();
    setTimeout(() => win.print(), 500);
    return { success: true };
  } catch (e) {
    return { success: false, error: e.message };
  }
}

export function printCurrentReport(exportPack) { return openPrintWindow(exportPack); }
