// ============================================================
// AP3X — reportExportUtils.js — Run 6
// ============================================================

import { formatReportForExport, generateExecutiveSummary, generateTechnicalSummary, generateBuildReadinessSummary } from "../core/reportGenerator.js";
import { ORIGINALITY_NOTICE } from "../core/originalityGuardEngine.js";

// ── JSON export ───────────────────────────────────────────────
export function exportReportAsJSON(report) {
  const clean = formatReportForExport(report);
  return JSON.stringify(clean, null, 2);
}

// ── Markdown export ───────────────────────────────────────────
export function exportReportAsMarkdown(report) {
  if (!report) return "# No report available\n";
  const R = report;
  const now = new Date().toLocaleString();

  const h1 = (t) => `# ${t}\n`;
  const h2 = (t) => `\n## ${t}\n`;
  const h3 = (t) => `\n### ${t}\n`;
  const li  = (t) => `- ${t}`;
  const br  = () => "\n---\n";

  let md = "";
  md += h1(`AP3X Architecture Intelligence Report`);
  md += `**Generated:** ${now}  \n`;
  md += `**App Type:** ${R.appType?.primary || "Unknown"}  \n`;
  md += `**Confidence:** ${R.confidenceScore || 0}%  \n`;
  md += br();

  md += h2("Executive Summary");
  md += generateExecutiveSummary(R) + "\n";

  md += h2("Technical Summary");
  md += generateTechnicalSummary(R) + "\n";

  md += h2("Build Readiness");
  md += generateBuildReadinessSummary(R) + "\n";

  md += h2("App Type Classification");
  md += `**Primary:** ${R.appType?.primary || "Unknown"}  \n`;
  if ((R.appType?.secondary || []).length > 0) {
    md += `**Secondary:** ${R.appType.secondary.join(", ")}  \n`;
  }

  md += h2("Core Modules");
  (R.modules || []).forEach((m) => {
    md += li(`**${m.name}** (${m.detected ? "detected" : "inferred"}, confidence: ${m.confidence}%) — ${m.description}`) + "\n";
  });

  md += h2("Screen / Page Map");
  (R.screens || []).forEach((s) => {
    md += li(`**${s.name}** [${s.type}] — ${s.description}`) + "\n";
  });

  md += h2("User Journeys");
  (R.userJourneys || []).forEach((j) => {
    md += h3(j.name);
    (j.steps || []).forEach((step) => { md += li(step) + "\n"; });
  });

  md += h2("Data Entities");
  (R.dataEntities || []).forEach((e) => {
    md += h3(e.name);
    md += `Fields: ${(e.fields || []).join(", ")}  \n`;
    md += `Source: ${e.source}  \n`;
  });

  md += h2("Business Rules");
  (R.businessRules || []).forEach((r) => {
    md += li(`**${r.rule}** (${r.origin}) — ${r.description}`) + "\n";
  });

  md += h2("Security Notes");
  (R.securityNeeds || []).forEach((s) => {
    md += li(`**${s.area}** [${s.status}] — ${s.description}`) + "\n";
  });

  md += h2("Missing Systems");
  if ((R.missingSystems || []).length === 0) {
    md += "No critical missing systems detected.\n";
  } else {
    (R.missingSystems || []).forEach((m) => {
      md += li(`**${m.system}** [${m.severity}] — ${m.note}`) + "\n";
    });
  }

  md += h2("Risk Warnings");
  if ((R.riskWarnings || []).length === 0) {
    md += "No validation warnings.\n";
  } else {
    ["critical","high","medium","low"].forEach((sev) => {
      const items = (R.riskWarnings || []).filter((w) => w.severity === sev);
      if (items.length === 0) return;
      md += h3(`${sev.toUpperCase()} (${items.length})`);
      items.forEach((w) => {
        md += li(`**${w.title}** — ${w.description}  \n  Fix: ${w.recommendedFix}${w.blocking ? " ⛔ BLOCKING" : ""}`) + "\n";
      });
    });
  }

  md += h2("Originality & Legal Safety Notice");
  md += `> ${ORIGINALITY_NOTICE}\n`;

  md += h2("Original Rebuild Blueprint");
  const bp = R.rebuildBlueprint;
  if (!bp) {
    md += "Blueprint not yet generated.\n";
  } else {
    md += `> ${bp.notice || ""}\n\n`;

    md += h3("Suggested Implementation Runs");
    (bp.implementationRuns || []).forEach((r) => {
      md += li(`**Run ${r.run} — ${r.title}:** ${r.description}`) + "\n";
    });

    md += h3("Suggested File Structure");
    md += "```\n" + (bp.fileStructure || "") + "\n```\n";

    md += h3("State Management");
    if (bp.stateManagement) {
      md += li(`Pattern: ${bp.stateManagement.pattern}`) + "\n";
      md += li(`Store File: ${bp.stateManagement.storeFile}`) + "\n";
      md += li(`Store Key: ${bp.stateManagement.storeKey}`) + "\n";
    }
  }

  md += br();
  md += `*Generated by AP3X BUILD CONTROL OS™ Architecture Intelligence — Run 6.*\n`;
  md += `*Architecture patterns only. Not a clone blueprint. Original implementation required.*\n`;

  return md;
}

// ── Copy to clipboard ─────────────────────────────────────────
export async function copyReportToClipboard(report, format = "json") {
  const text = format === "markdown" ? exportReportAsMarkdown(report) : exportReportAsJSON(report);
  try {
    if (navigator?.clipboard?.writeText) {
      await navigator.clipboard.writeText(text);
      return { success: true };
    }
    // Fallback: execCommand
    const el = document.createElement("textarea");
    el.value = text;
    el.style.position = "fixed"; el.style.opacity = "0";
    document.body.appendChild(el); el.focus(); el.select();
    const ok = document.execCommand("copy");
    document.body.removeChild(el);
    return { success: ok, fallback: true };
  } catch (e) {
    return { success: false, error: e.message };
  }
}

// ── Download file ─────────────────────────────────────────────
export function downloadReportFile(report, format = "json") {
  try {
    const text     = format === "markdown" ? exportReportAsMarkdown(report) : exportReportAsJSON(report);
    const mimeType = format === "markdown" ? "text/markdown" : "application/json";
    const ext      = format === "markdown" ? "md" : "json";
    const name     = `ap3x-architecture-report-${Date.now()}.${ext}`;
    const blob     = new Blob([text], { type: mimeType });
    const url      = URL.createObjectURL(blob);
    const a        = document.createElement("a");
    a.href = url; a.download = name;
    document.body.appendChild(a); a.click();
    setTimeout(() => { URL.revokeObjectURL(url); document.body.removeChild(a); }, 500);
    return { success: true };
  } catch (e) {
    return { success: false, error: e.message };
  }
}
